FROM pbaumgartner/cdc-text-classification

# Decompress Model Files (this takes some time)
RUN mkdir --parents /submission/model && \
    cd /workspace/ && \
    for file in *.tar.xz; do echo "extracting $file"; tar -C /submission/model -Jxf "$file"; rm "$file"; done

# Cleanup
RUN rm -rf /workspace/

# Install Symspell (forgot in requirements.txt)
RUN pip install symspellpy==6.5.2

WORKDIR /app
COPY . /app

RUN chmod -R +x *
